<?php 
	session_start();
	$products = array(
		'SP01'=>array(
			'MaSp'=>"SP01",
			'TenSp'=>"Iphone5",
			'GiaTien'=>3000000,
			'SoLuong'=>100,
			'Anh'=>'https://www.didongviet.vn/pub/media/catalog/product//i/p/iphone-6-plus-16gb-quoc-te-like-new-didongviet-1.jpg',
		),
		'SP02'=>array(
			'MaSp'=>"SP02",
			'TenSp'=>"Iphone6",
			'GiaTien'=>6000000,
			'SoLuong'=>30,
			'Anh'=>'https://www.didongviet.vn/pub/media/catalog/product//i/p/iphone-6-plus-16gb-quoc-te-like-new-didongviet-1.jpg',
		),
		'SP03'=>array(
			'MaSp'=>"SP03",
			'TenSp'=>"Iphone7",
			'GiaTien'=>7000000,
			'SoLuong'=>20,
			'Anh'=>'https://www.didongviet.vn/pub/media/catalog/product//i/p/iphone-6-plus-16gb-quoc-te-like-new-didongviet-1.jpg',
		),
		'SP04'=>array(
			'MaSp'=>"SP04",
			'TenSp'=>"Iphone8",
			'GiaTien'=>8000000,
			'SoLuong'=>80,
			'Anh'=>'https://www.didongviet.vn/pub/media/catalog/product//i/p/iphone-6-plus-16gb-quoc-te-like-new-didongviet-1.jpg',
		),
		'SP05'=>array(
			'MaSp'=>"SP05",
			'TenSp'=>"IphoneX",
			'GiaTien'=>10000000,
			'SoLuong'=>10,
			'Anh'=>'https://www.didongviet.vn/pub/media/catalog/product//i/p/iphone-6-plus-16gb-quoc-te-like-new-didongviet-1.jpg',
		),
	);
 ?>